# VeriTiger-V19P-A14, xcvu19p_CIV-fsva3824-1-e.
# SI5338 differential pairs are AC coupled and externally terminated.

# EH2 core clock: GCLK0_FPGA_TOP (GCCLKT0), configured to 50 MHz.
set_property PACKAGE_PIN BY44 [get_ports core_clk_p]
set_property PACKAGE_PIN CA44 [get_ports core_clk_n]
set_property IOSTANDARD LVDS [get_ports {core_clk_p core_clk_n}]
create_clock -period 20.000 -name core_clk [get_ports core_clk_p]

# ATG management clock: GCLK1_FPGA_TOP, 100 MHz (same as MAC project).
set_property PACKAGE_PIN BN55 [get_ports atg_clk_p]
set_property PACKAGE_PIN BP55 [get_ports atg_clk_n]
set_property IOSTANDARD LVDS [get_ports {atg_clk_p atg_clk_n}]
create_clock -period 10.000 -name atg_clk [get_ports atg_clk_p]

# GCLK0, GCLK1 and the two GCLK3 oscillators are physically independent.
# Include all MIG-generated descendants in their respective asynchronous
# groups; AXI Clock Converter IPs provide the required CDC structures.
set_clock_groups -asynchronous \
  -group [get_clocks -include_generated_clocks core_clk] \
  -group [get_clocks -include_generated_clocks atg_clk] \
  -group [get_clocks -include_generated_clocks -of_objects [get_ports c0_sys_clk_p]] \
  -group [get_clocks -include_generated_clocks -of_objects [get_ports c1_sys_clk_p]]

# Board reset convention inherited from the MAC project.
set_property PACKAGE_PIN BU21 [get_ports sw3_1]
set_property PACKAGE_PIN BU28 [get_ports sw4_1]
set_property IOSTANDARD LVCMOS12 [get_ports {sw3_1 sw4_1}]

# User LED banks T1..T4 and B1..B4. All eight LEDs are active high.
# LED0/1=DDR0/1 ATG write plus initialization readback passed.
# LED2/3=IFU request/normal read response seen.
# LED4/5=LSU read request/normal read response seen.
# LED6=LSU write request seen, LED7=final DDR result check passed.
set_property PACKAGE_PIN BE22 [get_ports {led[0]}]
set_property PACKAGE_PIN BG23 [get_ports {led[1]}]
set_property PACKAGE_PIN BJ20 [get_ports {led[2]}]
set_property PACKAGE_PIN BN19 [get_ports {led[3]}]
set_property PACKAGE_PIN U34  [get_ports {led[4]}]
set_property PACKAGE_PIN T37  [get_ports {led[5]}]
set_property PACKAGE_PIN K37  [get_ports {led[6]}]
set_property PACKAGE_PIN M39  [get_ports {led[7]}]
set_property IOSTANDARD LVCMOS12 [get_ports {led[*]}]
set_property DRIVE 8 [get_ports {led[*]}]

# DDR4-1 MIG reference: GCLK3_FPGA_TOP, 76.15 MHz.
set_property PACKAGE_PIN BN26 [get_ports c0_sys_clk_p]
set_property PACKAGE_PIN BP26 [get_ports c0_sys_clk_n]

set_property PACKAGE_PIN BW33 [get_ports {c0_ddr4_dq[0]}]
set_property PACKAGE_PIN BW31 [get_ports {c0_ddr4_dq[1]}]
set_property PACKAGE_PIN BV31 [get_ports {c0_ddr4_dq[2]}]
set_property PACKAGE_PIN BV30 [get_ports {c0_ddr4_dq[3]}]
set_property PACKAGE_PIN BV34 [get_ports {c0_ddr4_dq[4]}]
set_property PACKAGE_PIN BV33 [get_ports {c0_ddr4_dq[5]}]
set_property PACKAGE_PIN BW32 [get_ports {c0_ddr4_dq[6]}]
set_property PACKAGE_PIN BW30 [get_ports {c0_ddr4_dq[7]}]
set_property PACKAGE_PIN BF21 [get_ports {c0_ddr4_dq[8]}]
set_property PACKAGE_PIN BG22 [get_ports {c0_ddr4_dq[9]}]
set_property PACKAGE_PIN BG21 [get_ports {c0_ddr4_dq[10]}]
set_property PACKAGE_PIN BF24 [get_ports {c0_ddr4_dq[11]}]
set_property PACKAGE_PIN BE24 [get_ports {c0_ddr4_dq[12]}]
set_property PACKAGE_PIN BH24 [get_ports {c0_ddr4_dq[13]}]
set_property PACKAGE_PIN BG24 [get_ports {c0_ddr4_dq[14]}]
set_property PACKAGE_PIN BF22 [get_ports {c0_ddr4_dq[15]}]
set_property PACKAGE_PIN BV28 [get_ports {c0_ddr4_dq[16]}]
set_property PACKAGE_PIN BV29 [get_ports {c0_ddr4_dq[17]}]
set_property PACKAGE_PIN BW27 [get_ports {c0_ddr4_dq[18]}]
set_property PACKAGE_PIN BY27 [get_ports {c0_ddr4_dq[19]}]
set_property PACKAGE_PIN BV26 [get_ports {c0_ddr4_dq[20]}]
set_property PACKAGE_PIN BV25 [get_ports {c0_ddr4_dq[21]}]
set_property PACKAGE_PIN BW28 [get_ports {c0_ddr4_dq[22]}]
set_property PACKAGE_PIN BY28 [get_ports {c0_ddr4_dq[23]}]
set_property PACKAGE_PIN CA27 [get_ports {c0_ddr4_dq[24]}]
set_property PACKAGE_PIN CC26 [get_ports {c0_ddr4_dq[25]}]
set_property PACKAGE_PIN CC25 [get_ports {c0_ddr4_dq[26]}]
set_property PACKAGE_PIN CA24 [get_ports {c0_ddr4_dq[27]}]
set_property PACKAGE_PIN CB27 [get_ports {c0_ddr4_dq[28]}]
set_property PACKAGE_PIN CA26 [get_ports {c0_ddr4_dq[29]}]
set_property PACKAGE_PIN CB26 [get_ports {c0_ddr4_dq[30]}]
set_property PACKAGE_PIN CA25 [get_ports {c0_ddr4_dq[31]}]
set_property PACKAGE_PIN BP22 [get_ports {c0_ddr4_dq[32]}]
set_property PACKAGE_PIN BR19 [get_ports {c0_ddr4_dq[33]}]
set_property PACKAGE_PIN BR20 [get_ports {c0_ddr4_dq[34]}]
set_property PACKAGE_PIN BP21 [get_ports {c0_ddr4_dq[35]}]
set_property PACKAGE_PIN BR22 [get_ports {c0_ddr4_dq[36]}]
set_property PACKAGE_PIN BR23 [get_ports {c0_ddr4_dq[37]}]
set_property PACKAGE_PIN BT20 [get_ports {c0_ddr4_dq[38]}]
set_property PACKAGE_PIN BT21 [get_ports {c0_ddr4_dq[39]}]
set_property PACKAGE_PIN BK22 [get_ports {c0_ddr4_dq[40]}]
set_property PACKAGE_PIN BH23 [get_ports {c0_ddr4_dq[41]}]
set_property PACKAGE_PIN BH19 [get_ports {c0_ddr4_dq[42]}]
set_property PACKAGE_PIN BK19 [get_ports {c0_ddr4_dq[43]}]
set_property PACKAGE_PIN BJ22 [get_ports {c0_ddr4_dq[44]}]
set_property PACKAGE_PIN BJ23 [get_ports {c0_ddr4_dq[45]}]
set_property PACKAGE_PIN BH20 [get_ports {c0_ddr4_dq[46]}]
set_property PACKAGE_PIN BK20 [get_ports {c0_ddr4_dq[47]}]
set_property PACKAGE_PIN CA30 [get_ports {c0_ddr4_dq[48]}]
set_property PACKAGE_PIN CB33 [get_ports {c0_ddr4_dq[49]}]
set_property PACKAGE_PIN CC28 [get_ports {c0_ddr4_dq[50]}]
set_property PACKAGE_PIN CA31 [get_ports {c0_ddr4_dq[51]}]
set_property PACKAGE_PIN CC33 [get_ports {c0_ddr4_dq[52]}]
set_property PACKAGE_PIN CC30 [get_ports {c0_ddr4_dq[53]}]
set_property PACKAGE_PIN CC29 [get_ports {c0_ddr4_dq[54]}]
set_property PACKAGE_PIN CC31 [get_ports {c0_ddr4_dq[55]}]
set_property PACKAGE_PIN BL22 [get_ports {c0_ddr4_dq[56]}]
set_property PACKAGE_PIN BM21 [get_ports {c0_ddr4_dq[57]}]
set_property PACKAGE_PIN BL20 [get_ports {c0_ddr4_dq[58]}]
set_property PACKAGE_PIN BL21 [get_ports {c0_ddr4_dq[59]}]
set_property PACKAGE_PIN BP23 [get_ports {c0_ddr4_dq[60]}]
set_property PACKAGE_PIN BN23 [get_ports {c0_ddr4_dq[61]}]
set_property PACKAGE_PIN BM22 [get_ports {c0_ddr4_dq[62]}]
set_property PACKAGE_PIN BL19 [get_ports {c0_ddr4_dq[63]}]
set_property PACKAGE_PIN BT29 [get_ports {c0_ddr4_dq[64]}]
set_property PACKAGE_PIN BR29 [get_ports {c0_ddr4_dq[65]}]
set_property PACKAGE_PIN BT25 [get_ports {c0_ddr4_dq[66]}]
set_property PACKAGE_PIN BR25 [get_ports {c0_ddr4_dq[67]}]
set_property PACKAGE_PIN BR28 [get_ports {c0_ddr4_dq[68]}]
set_property PACKAGE_PIN BR24 [get_ports {c0_ddr4_dq[69]}]
set_property PACKAGE_PIN BR27 [get_ports {c0_ddr4_dq[70]}]
set_property PACKAGE_PIN BT26 [get_ports {c0_ddr4_dq[71]}]
set_property PACKAGE_PIN BF29 [get_ports {c0_ddr4_adr[0]}]
set_property PACKAGE_PIN BN29 [get_ports {c0_ddr4_adr[1]}]
set_property PACKAGE_PIN BP25 [get_ports {c0_ddr4_adr[2]}]
set_property PACKAGE_PIN BM28 [get_ports {c0_ddr4_adr[3]}]
set_property PACKAGE_PIN BL26 [get_ports {c0_ddr4_adr[4]}]
set_property PACKAGE_PIN BM26 [get_ports {c0_ddr4_adr[5]}]
set_property PACKAGE_PIN BM29 [get_ports {c0_ddr4_adr[6]}]
set_property PACKAGE_PIN BM27 [get_ports {c0_ddr4_adr[7]}]
set_property PACKAGE_PIN BL27 [get_ports {c0_ddr4_adr[8]}]
set_property PACKAGE_PIN BH29 [get_ports {c0_ddr4_adr[9]}]
set_property PACKAGE_PIN BJ25 [get_ports {c0_ddr4_adr[10]}]
set_property PACKAGE_PIN BN28 [get_ports {c0_ddr4_adr[11]}]
set_property PACKAGE_PIN BG29 [get_ports {c0_ddr4_adr[12]}]
set_property PACKAGE_PIN BE25 [get_ports {c0_ddr4_adr[13]}]
set_property PACKAGE_PIN BH25 [get_ports {c0_ddr4_adr[14]}]
set_property PACKAGE_PIN BG26 [get_ports {c0_ddr4_adr[15]}]
set_property PACKAGE_PIN BF25 [get_ports {c0_ddr4_adr[16]}]
set_property PACKAGE_PIN BY30 [get_ports {c0_ddr4_dm_dbi_n[0]}]
set_property PACKAGE_PIN BE23 [get_ports {c0_ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN BU29 [get_ports {c0_ddr4_dm_dbi_n[2]}]
set_property PACKAGE_PIN BY25 [get_ports {c0_ddr4_dm_dbi_n[3]}]
set_property PACKAGE_PIN BT22 [get_ports {c0_ddr4_dm_dbi_n[4]}]
set_property PACKAGE_PIN BH21 [get_ports {c0_ddr4_dm_dbi_n[5]}]
set_property PACKAGE_PIN CA29 [get_ports {c0_ddr4_dm_dbi_n[6]}]
set_property PACKAGE_PIN BM19 [get_ports {c0_ddr4_dm_dbi_n[7]}]
set_property PACKAGE_PIN BT24 [get_ports {c0_ddr4_dm_dbi_n[8]}]
set_property PACKAGE_PIN BK27 [get_ports {c0_ddr4_ba[0]}]
set_property PACKAGE_PIN BP27 [get_ports {c0_ddr4_ba[1]}]
set_property PACKAGE_PIN BE27 [get_ports {c0_ddr4_bg[0]}]
set_property PACKAGE_PIN BF26 [get_ports {c0_ddr4_bg[1]}]
set_property PACKAGE_PIN BL29 [get_ports c0_ddr4_act_n]
set_property PACKAGE_PIN BM23 [get_ports c0_ddr4_reset_n]
set_property PACKAGE_PIN BJ28 [get_ports {c0_ddr4_cs_n[0]}]
set_property PACKAGE_PIN BE28 [get_ports {c0_ddr4_cke[0]}]
set_property PACKAGE_PIN BK29 [get_ports {c0_ddr4_odt[0]}]
set_property PACKAGE_PIN BK25 [get_ports {c0_ddr4_ck_t[0]}]
set_property PACKAGE_PIN BL25 [get_ports {c0_ddr4_ck_c[0]}]
set_property PACKAGE_PIN BY33 [get_ports {c0_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN BY34 [get_ports {c0_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN BF20 [get_ports {c0_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN BE20 [get_ports {c0_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN BW25 [get_ports {c0_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN BW26 [get_ports {c0_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN CC24 [get_ports {c0_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN CB24 [get_ports {c0_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN BU22 [get_ports {c0_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN BU23 [get_ports {c0_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN BK23 [get_ports {c0_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN BK24 [get_ports {c0_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN CB32 [get_ports {c0_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN CA32 [get_ports {c0_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN BN20 [get_ports {c0_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN BN21 [get_ports {c0_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN BU26 [get_ports {c0_ddr4_dqs_c[8]}]
set_property PACKAGE_PIN BT27 [get_ports {c0_ddr4_dqs_t[8]}]

# DDR4-2 MIG reference: GCLK3_FPGA_BOT, 76.15 MHz.
set_property PACKAGE_PIN F32 [get_ports c1_sys_clk_p]
set_property PACKAGE_PIN E32 [get_ports c1_sys_clk_n]

set_property PACKAGE_PIN W28 [get_ports {c1_ddr4_dq[0]}]
set_property PACKAGE_PIN V29 [get_ports {c1_ddr4_dq[1]}]
set_property PACKAGE_PIN R29 [get_ports {c1_ddr4_dq[2]}]
set_property PACKAGE_PIN T27 [get_ports {c1_ddr4_dq[3]}]
set_property PACKAGE_PIN V28 [get_ports {c1_ddr4_dq[4]}]
set_property PACKAGE_PIN V30 [get_ports {c1_ddr4_dq[5]}]
set_property PACKAGE_PIN U27 [get_ports {c1_ddr4_dq[6]}]
set_property PACKAGE_PIN R30 [get_ports {c1_ddr4_dq[7]}]
set_property PACKAGE_PIN T31 [get_ports {c1_ddr4_dq[8]}]
set_property PACKAGE_PIN W30 [get_ports {c1_ddr4_dq[9]}]
set_property PACKAGE_PIN U32 [get_ports {c1_ddr4_dq[10]}]
set_property PACKAGE_PIN V33 [get_ports {c1_ddr4_dq[11]}]
set_property PACKAGE_PIN T32 [get_ports {c1_ddr4_dq[12]}]
set_property PACKAGE_PIN U31 [get_ports {c1_ddr4_dq[13]}]
set_property PACKAGE_PIN U33 [get_ports {c1_ddr4_dq[14]}]
set_property PACKAGE_PIN W31 [get_ports {c1_ddr4_dq[15]}]
set_property PACKAGE_PIN L27 [get_ports {c1_ddr4_dq[16]}]
set_property PACKAGE_PIN M29 [get_ports {c1_ddr4_dq[17]}]
set_property PACKAGE_PIN N30 [get_ports {c1_ddr4_dq[18]}]
set_property PACKAGE_PIN P30 [get_ports {c1_ddr4_dq[19]}]
set_property PACKAGE_PIN M27 [get_ports {c1_ddr4_dq[20]}]
set_property PACKAGE_PIN P27 [get_ports {c1_ddr4_dq[21]}]
set_property PACKAGE_PIN M28 [get_ports {c1_ddr4_dq[22]}]
set_property PACKAGE_PIN P28 [get_ports {c1_ddr4_dq[23]}]
set_property PACKAGE_PIN M31 [get_ports {c1_ddr4_dq[24]}]
set_property PACKAGE_PIN P31 [get_ports {c1_ddr4_dq[25]}]
set_property PACKAGE_PIN K33 [get_ports {c1_ddr4_dq[26]}]
set_property PACKAGE_PIN N33 [get_ports {c1_ddr4_dq[27]}]
set_property PACKAGE_PIN M32 [get_ports {c1_ddr4_dq[28]}]
set_property PACKAGE_PIN N31 [get_ports {c1_ddr4_dq[29]}]
set_property PACKAGE_PIN K32 [get_ports {c1_ddr4_dq[30]}]
set_property PACKAGE_PIN M33 [get_ports {c1_ddr4_dq[31]}]
set_property PACKAGE_PIN R34 [get_ports {c1_ddr4_dq[32]}]
set_property PACKAGE_PIN T36 [get_ports {c1_ddr4_dq[33]}]
set_property PACKAGE_PIN W37 [get_ports {c1_ddr4_dq[34]}]
set_property PACKAGE_PIN R35 [get_ports {c1_ddr4_dq[35]}]
set_property PACKAGE_PIN U36 [get_ports {c1_ddr4_dq[36]}]
set_property PACKAGE_PIN W36 [get_ports {c1_ddr4_dq[37]}]
set_property PACKAGE_PIN V36 [get_ports {c1_ddr4_dq[38]}]
set_property PACKAGE_PIN V35 [get_ports {c1_ddr4_dq[39]}]
set_property PACKAGE_PIN N40 [get_ports {c1_ddr4_dq[40]}]
set_property PACKAGE_PIN P38 [get_ports {c1_ddr4_dq[41]}]
set_property PACKAGE_PIN P37 [get_ports {c1_ddr4_dq[42]}]
set_property PACKAGE_PIN L37 [get_ports {c1_ddr4_dq[43]}]
set_property PACKAGE_PIN R37 [get_ports {c1_ddr4_dq[44]}]
set_property PACKAGE_PIN N38 [get_ports {c1_ddr4_dq[45]}]
set_property PACKAGE_PIN P40 [get_ports {c1_ddr4_dq[46]}]
set_property PACKAGE_PIN M37 [get_ports {c1_ddr4_dq[47]}]
set_property PACKAGE_PIN N35 [get_ports {c1_ddr4_dq[48]}]
set_property PACKAGE_PIN L34 [get_ports {c1_ddr4_dq[49]}]
set_property PACKAGE_PIN M34 [get_ports {c1_ddr4_dq[50]}]
set_property PACKAGE_PIN N34 [get_ports {c1_ddr4_dq[51]}]
set_property PACKAGE_PIN L35 [get_ports {c1_ddr4_dq[52]}]
set_property PACKAGE_PIN L36 [get_ports {c1_ddr4_dq[53]}]
set_property PACKAGE_PIN N36 [get_ports {c1_ddr4_dq[54]}]
set_property PACKAGE_PIN M36 [get_ports {c1_ddr4_dq[55]}]
set_property PACKAGE_PIN V40 [get_ports {c1_ddr4_dq[56]}]
set_property PACKAGE_PIN T40 [get_ports {c1_ddr4_dq[57]}]
set_property PACKAGE_PIN W38 [get_ports {c1_ddr4_dq[58]}]
set_property PACKAGE_PIN U37 [get_ports {c1_ddr4_dq[59]}]
set_property PACKAGE_PIN U38 [get_ports {c1_ddr4_dq[60]}]
set_property PACKAGE_PIN T39 [get_ports {c1_ddr4_dq[61]}]
set_property PACKAGE_PIN V38 [get_ports {c1_ddr4_dq[62]}]
set_property PACKAGE_PIN W40 [get_ports {c1_ddr4_dq[63]}]
set_property PACKAGE_PIN B27 [get_ports {c1_ddr4_dq[64]}]
set_property PACKAGE_PIN D30 [get_ports {c1_ddr4_dq[65]}]
set_property PACKAGE_PIN C30 [get_ports {c1_ddr4_dq[66]}]
set_property PACKAGE_PIN B28 [get_ports {c1_ddr4_dq[67]}]
set_property PACKAGE_PIN C29 [get_ports {c1_ddr4_dq[68]}]
set_property PACKAGE_PIN E30 [get_ports {c1_ddr4_dq[69]}]
set_property PACKAGE_PIN A27 [get_ports {c1_ddr4_dq[70]}]
set_property PACKAGE_PIN B29 [get_ports {c1_ddr4_dq[71]}]
set_property PACKAGE_PIN B32 [get_ports {c1_ddr4_adr[0]}]
set_property PACKAGE_PIN F27 [get_ports {c1_ddr4_adr[1]}]
set_property PACKAGE_PIN D31 [get_ports {c1_ddr4_adr[2]}]
set_property PACKAGE_PIN G27 [get_ports {c1_ddr4_adr[3]}]
set_property PACKAGE_PIN H29 [get_ports {c1_ddr4_adr[4]}]
set_property PACKAGE_PIN B31 [get_ports {c1_ddr4_adr[5]}]
set_property PACKAGE_PIN C31 [get_ports {c1_ddr4_adr[6]}]
set_property PACKAGE_PIN E27 [get_ports {c1_ddr4_adr[7]}]
set_property PACKAGE_PIN F30 [get_ports {c1_ddr4_adr[8]}]
set_property PACKAGE_PIN D27 [get_ports {c1_ddr4_adr[9]}]
set_property PACKAGE_PIN F31 [get_ports {c1_ddr4_adr[10]}]
set_property PACKAGE_PIN G28 [get_ports {c1_ddr4_adr[11]}]
set_property PACKAGE_PIN E28 [get_ports {c1_ddr4_adr[12]}]
set_property PACKAGE_PIN H33 [get_ports {c1_ddr4_adr[13]}]
set_property PACKAGE_PIN G29 [get_ports {c1_ddr4_adr[14]}]
set_property PACKAGE_PIN G33 [get_ports {c1_ddr4_adr[15]}]
set_property PACKAGE_PIN J33 [get_ports {c1_ddr4_adr[16]}]
set_property PACKAGE_PIN T30 [get_ports {c1_ddr4_dm_dbi_n[0]}]
set_property PACKAGE_PIN W33 [get_ports {c1_ddr4_dm_dbi_n[1]}]
set_property PACKAGE_PIN L30 [get_ports {c1_ddr4_dm_dbi_n[2]}]
set_property PACKAGE_PIN P33 [get_ports {c1_ddr4_dm_dbi_n[3]}]
set_property PACKAGE_PIN V34 [get_ports {c1_ddr4_dm_dbi_n[4]}]
set_property PACKAGE_PIN N39 [get_ports {c1_ddr4_dm_dbi_n[5]}]
set_property PACKAGE_PIN P35 [get_ports {c1_ddr4_dm_dbi_n[6]}]
set_property PACKAGE_PIN R39 [get_ports {c1_ddr4_dm_dbi_n[7]}]
set_property PACKAGE_PIN D28 [get_ports {c1_ddr4_dm_dbi_n[8]}]
set_property PACKAGE_PIN J31 [get_ports {c1_ddr4_ba[0]}]
set_property PACKAGE_PIN J27 [get_ports {c1_ddr4_ba[1]}]
set_property PACKAGE_PIN E29 [get_ports {c1_ddr4_bg[0]}]
set_property PACKAGE_PIN K28 [get_ports {c1_ddr4_bg[1]}]
set_property PACKAGE_PIN J28 [get_ports c1_ddr4_act_n]
set_property PACKAGE_PIN M38 [get_ports c1_ddr4_reset_n]
set_property PACKAGE_PIN H31 [get_ports {c1_ddr4_cs_n[0]}]
set_property PACKAGE_PIN K29 [get_ports {c1_ddr4_cke[0]}]
set_property PACKAGE_PIN C33 [get_ports {c1_ddr4_odt[0]}]
set_property PACKAGE_PIN A32 [get_ports {c1_ddr4_ck_t[0]}]
set_property PACKAGE_PIN A31 [get_ports {c1_ddr4_ck_c[0]}]
set_property PACKAGE_PIN U28 [get_ports {c1_ddr4_dqs_c[0]}]
set_property PACKAGE_PIN U29 [get_ports {c1_ddr4_dqs_t[0]}]
set_property PACKAGE_PIN R32 [get_ports {c1_ddr4_dqs_c[1]}]
set_property PACKAGE_PIN R33 [get_ports {c1_ddr4_dqs_t[1]}]
set_property PACKAGE_PIN N28 [get_ports {c1_ddr4_dqs_c[2]}]
set_property PACKAGE_PIN N29 [get_ports {c1_ddr4_dqs_t[2]}]
set_property PACKAGE_PIN L31 [get_ports {c1_ddr4_dqs_c[3]}]
set_property PACKAGE_PIN L32 [get_ports {c1_ddr4_dqs_t[3]}]
set_property PACKAGE_PIN T35 [get_ports {c1_ddr4_dqs_c[4]}]
set_property PACKAGE_PIN T34 [get_ports {c1_ddr4_dqs_t[4]}]
set_property PACKAGE_PIN L40 [get_ports {c1_ddr4_dqs_c[5]}]
set_property PACKAGE_PIN L39 [get_ports {c1_ddr4_dqs_t[5]}]
set_property PACKAGE_PIN K35 [get_ports {c1_ddr4_dqs_c[6]}]
set_property PACKAGE_PIN K34 [get_ports {c1_ddr4_dqs_t[6]}]
set_property PACKAGE_PIN U39 [get_ports {c1_ddr4_dqs_c[7]}]
set_property PACKAGE_PIN V39 [get_ports {c1_ddr4_dqs_t[7]}]
set_property PACKAGE_PIN A29 [get_ports {c1_ddr4_dqs_c[8]}]
set_property PACKAGE_PIN A30 [get_ports {c1_ddr4_dqs_t[8]}]

set_property BITSTREAM.GENERAL.COMPRESS TRUE [current_design]
