// SPDX-License-Identifier: Apache-2.0
`timescale 1ns/1ps

// 128 KiB true-dual-port program/data RAM and two AXI4 slave front ends.
// Port A is read-only for IFU. Port B services LSU reads and writes.
module eh2_unified_axi_bram #(
    parameter integer MEM_BYTES = 131072,
    parameter logic [31:0] BASE_ADDR = 32'h8000_0000,
    parameter integer IFU_TAG_WIDTH = 4,
    parameter integer LSU_TAG_WIDTH = 4,
    parameter string MEM_FILE = "",
    parameter logic SPARSE_AUX_ENABLE = 1'b0,
    parameter logic [31:0] SPARSE_AUX_ADDR = 32'h8001_0000,
    parameter logic [63:0] SPARSE_AUX_INIT = 64'b0
) (
    input  logic                         clk,
    input  logic                         rst_l,

    input  logic                         ifu_arvalid,
    output logic                         ifu_arready,
    input  logic [31:0]                  ifu_araddr,
    input  logic [IFU_TAG_WIDTH-1:0]     ifu_arid,
    input  logic [7:0]                   ifu_arlen,
    input  logic [1:0]                   ifu_arburst,
    input  logic [2:0]                   ifu_arsize,
    output logic                         ifu_rvalid,
    input  logic                         ifu_rready,
    output logic [63:0]                  ifu_rdata,
    output logic [1:0]                   ifu_rresp,
    output logic [IFU_TAG_WIDTH-1:0]     ifu_rid,
    output logic                         ifu_rlast,

    input  logic                         lsu_arvalid,
    output logic                         lsu_arready,
    input  logic [31:0]                  lsu_araddr,
    input  logic [LSU_TAG_WIDTH-1:0]     lsu_arid,
    input  logic [7:0]                   lsu_arlen,
    input  logic [1:0]                   lsu_arburst,
    input  logic [2:0]                   lsu_arsize,
    output logic                         lsu_rvalid,
    input  logic                         lsu_rready,
    output logic [63:0]                  lsu_rdata,
    output logic [1:0]                   lsu_rresp,
    output logic [LSU_TAG_WIDTH-1:0]     lsu_rid,
    output logic                         lsu_rlast,

    input  logic                         lsu_awvalid,
    output logic                         lsu_awready,
    input  logic [31:0]                  lsu_awaddr,
    input  logic [LSU_TAG_WIDTH-1:0]     lsu_awid,
    input  logic [7:0]                   lsu_awlen,
    input  logic [1:0]                   lsu_awburst,
    input  logic [2:0]                   lsu_awsize,
    input  logic                         lsu_wvalid,
    output logic                         lsu_wready,
    input  logic [63:0]                  lsu_wdata,
    input  logic [7:0]                   lsu_wstrb,
    input  logic                         lsu_wlast,
    output logic                         lsu_bvalid,
    input  logic                         lsu_bready,
    output logic [1:0]                   lsu_bresp,
    output logic [LSU_TAG_WIDTH-1:0]     lsu_bid
);
    localparam integer WORDS = MEM_BYTES / 8;
    localparam integer INDEX_WIDTH = $clog2(WORDS);

    (* ram_style = "block" *) logic [63:0] memory [0:WORDS-1];
    logic [63:0] sparse_aux_word;

    logic ifu_read_active;
    logic [31:0] ifu_read_addr;
    logic [7:0] ifu_beats_left;

    logic lsu_read_active;
    logic [31:0] lsu_read_addr;
    logic [7:0] lsu_beats_left;

    logic have_aw;
    logic [31:0] saved_awaddr;
    logic [LSU_TAG_WIDTH-1:0] saved_awid;
    logic have_w;
    logic [63:0] saved_wdata;
    logic [7:0] saved_wstrb;

    logic aw_handshake;
    logic w_handshake;
    logic write_fire;
    logic [31:0] effective_awaddr;
    logic [LSU_TAG_WIDTH-1:0] effective_awid;
    logic [63:0] effective_wdata;
    logic [7:0] effective_wstrb;
    logic write_response_available;

    integer byte_lane;
    integer aux_byte_lane;

    function automatic logic main_in_range(input logic [31:0] address);
        main_in_range = (address >= BASE_ADDR) &&
                        (address < (BASE_ADDR + MEM_BYTES));
    endfunction

    function automatic logic aux_in_range(input logic [31:0] address);
        aux_in_range = SPARSE_AUX_ENABLE &&
                       (address[31:3] == SPARSE_AUX_ADDR[31:3]);
    endfunction

    function automatic logic [INDEX_WIDTH-1:0] word_index(
        input logic [31:0] address
    );
        word_index = (address - BASE_ADDR) >> 3;
    endfunction

    initial begin
        if (MEM_FILE != "")
            $readmemh(MEM_FILE, memory, 0, WORDS-1);
    end

    assign ifu_arready = ~ifu_read_active;
    assign ifu_rresp = 2'b00;
    assign ifu_rlast = ifu_rvalid && (ifu_beats_left == 0);

    // IFU BRAM port. Incrementing bursts are the only form generated by EH2.
    always_ff @(posedge clk or negedge rst_l) begin
        if (!rst_l) begin
            ifu_read_active <= 1'b0;
            ifu_read_addr <= 32'b0;
            ifu_beats_left <= 8'b0;
            ifu_rvalid <= 1'b0;
            ifu_rid <= '0;
        end else begin
            if (ifu_arvalid && ifu_arready) begin
                ifu_read_active <= 1'b1;
                ifu_read_addr <= ifu_araddr;
                ifu_beats_left <= ifu_arlen;
                ifu_rid <= ifu_arid;
                ifu_rvalid <= 1'b1;
            end else if (ifu_rvalid && ifu_rready) begin
                if (ifu_beats_left == 0) begin
                    ifu_read_active <= 1'b0;
                    ifu_rvalid <= 1'b0;
                end else begin
                    ifu_read_addr <= ifu_read_addr + 32'd8;
                    ifu_beats_left <= ifu_beats_left - 8'd1;
                end
            end
        end
    end

    // BRAM port A: registered IFU reads.  Keep the memory access out of the
    // asynchronous-reset state process so it matches the native BRAM shape.
    always_ff @(posedge clk) begin
        if (rst_l) begin
            if (ifu_arvalid && ifu_arready)
                if (main_in_range(ifu_araddr))
                    ifu_rdata <= memory[word_index(ifu_araddr)];
                else if (aux_in_range(ifu_araddr))
                    ifu_rdata <= sparse_aux_word;
                else
                    ifu_rdata <= 64'b0;
            else if (ifu_rvalid && ifu_rready && (ifu_beats_left != 0))
                if (main_in_range(ifu_read_addr + 32'd8))
                    ifu_rdata <= memory[word_index(ifu_read_addr + 32'd8)];
                else if (aux_in_range(ifu_read_addr + 32'd8))
                    ifu_rdata <= sparse_aux_word;
                else
                    ifu_rdata <= 64'b0;
        end
    end

    assign write_response_available = ~lsu_bvalid | lsu_bready;
    assign lsu_awready = ~lsu_read_active && ~have_aw &&
                         write_response_available;
    assign lsu_wready = ~lsu_read_active && ~have_w &&
                        write_response_available;
    assign aw_handshake = lsu_awvalid && lsu_awready;
    assign w_handshake = lsu_wvalid && lsu_wready;
    assign effective_awaddr = have_aw ? saved_awaddr : lsu_awaddr;
    assign effective_awid = have_aw ? saved_awid : lsu_awid;
    assign effective_wdata = have_w ? saved_wdata : lsu_wdata;
    assign effective_wstrb = have_w ? saved_wstrb : lsu_wstrb;
    assign write_fire = (have_aw || aw_handshake) &&
                        (have_w || w_handshake) &&
                        write_response_available;

    // Give writes priority over a new LSU read, keeping BRAM port B to one
    // operation per cycle.
    assign lsu_arready = ~lsu_read_active && ~have_aw && ~have_w &&
                         ~lsu_awvalid && ~lsu_wvalid;
    assign lsu_rresp = 2'b00;
    assign lsu_rlast = lsu_rvalid && (lsu_beats_left == 0);
    assign lsu_bresp = 2'b00;

    always_ff @(posedge clk or negedge rst_l) begin
        if (!rst_l) begin
            lsu_read_active <= 1'b0;
            lsu_read_addr <= 32'b0;
            lsu_beats_left <= 8'b0;
            lsu_rvalid <= 1'b0;
            lsu_rid <= '0;
            have_aw <= 1'b0;
            saved_awaddr <= 32'b0;
            saved_awid <= '0;
            have_w <= 1'b0;
            saved_wdata <= 64'b0;
            saved_wstrb <= 8'b0;
            lsu_bvalid <= 1'b0;
            lsu_bid <= '0;
        end else begin
            if (lsu_bvalid && lsu_bready && !write_fire)
                lsu_bvalid <= 1'b0;

            if (write_fire) begin
                have_aw <= 1'b0;
                have_w <= 1'b0;
                lsu_bvalid <= 1'b1;
                lsu_bid <= effective_awid;
            end else begin
                if (aw_handshake) begin
                    have_aw <= 1'b1;
                    saved_awaddr <= lsu_awaddr;
                    saved_awid <= lsu_awid;
                end
                if (w_handshake) begin
                    have_w <= 1'b1;
                    saved_wdata <= lsu_wdata;
                    saved_wstrb <= lsu_wstrb;
                end
            end

            if (lsu_arvalid && lsu_arready) begin
                lsu_read_active <= 1'b1;
                lsu_read_addr <= lsu_araddr;
                lsu_beats_left <= lsu_arlen;
                lsu_rid <= lsu_arid;
                lsu_rvalid <= 1'b1;
            end else if (lsu_rvalid && lsu_rready) begin
                if (lsu_beats_left == 0) begin
                    lsu_read_active <= 1'b0;
                    lsu_rvalid <= 1'b0;
                end else begin
                    lsu_read_addr <= lsu_read_addr + 32'd8;
                    lsu_beats_left <= lsu_beats_left - 8'd1;
                end
            end
        end
    end

    // BRAM port B: LSU writes and registered reads.  All accesses for this
    // port live in one plain clocked process, which is the Vivado inference
    // template for a true dual-port RAM with byte write enables.
    always_ff @(posedge clk) begin
        if (rst_l) begin
            if (write_fire) begin
                if (main_in_range(effective_awaddr)) begin
                    for (byte_lane = 0; byte_lane < 8; byte_lane = byte_lane + 1)
                        if (effective_wstrb[byte_lane])
                            memory[word_index(effective_awaddr)][byte_lane*8 +: 8] <=
                                effective_wdata[byte_lane*8 +: 8];
                end
            end else if (lsu_arvalid && lsu_arready) begin
                if (main_in_range(lsu_araddr))
                    lsu_rdata <= memory[word_index(lsu_araddr)];
                else if (aux_in_range(lsu_araddr))
                    lsu_rdata <= sparse_aux_word;
                else
                    lsu_rdata <= 64'b0;
            end else if (lsu_rvalid && lsu_rready &&
                         (lsu_beats_left != 0)) begin
                if (main_in_range(lsu_read_addr + 32'd8))
                    lsu_rdata <= memory[word_index(lsu_read_addr + 32'd8)];
                else if (aux_in_range(lsu_read_addr + 32'd8))
                    lsu_rdata <= sparse_aux_word;
                else
                    lsu_rdata <= 64'b0;
            end
        end
    end

    // The optional sparse word fills the ELF's isolated data object without
    // allocating BRAM for the unused address hole.  It is intentionally a
    // small register bank, independent of the inferred main BRAM.
    always_ff @(posedge clk or negedge rst_l) begin
        if (!rst_l)
            sparse_aux_word <= SPARSE_AUX_INIT;
        else if (write_fire && aux_in_range(effective_awaddr)) begin
            for (aux_byte_lane = 0; aux_byte_lane < 8;
                 aux_byte_lane = aux_byte_lane + 1)
                if (effective_wstrb[aux_byte_lane])
                    sparse_aux_word[aux_byte_lane*8 +: 8] <=
                        effective_wdata[aux_byte_lane*8 +: 8];
        end
    end

    // Unused AXI attributes are intentionally accepted; EH2 emits INCR
    // bursts with 64-bit data on this integration.
    logic unused_attributes;
    always_comb unused_attributes = ^{ifu_arburst, ifu_arsize,
        lsu_arburst, lsu_arsize, lsu_awlen, lsu_awburst, lsu_awsize,
        lsu_wlast};
endmodule
