#!/usr/bin/env python3
"""Build fixed-size DDR and Ethernet test images from a raw program binary."""

from __future__ import annotations

import argparse
import json
from pathlib import Path


PROGRAM_DEST = bytes.fromhex("02 12 34 56 78 ff")
HOST_SOURCE = bytes.fromhex("02 32 05 25 00 fe")
PROGRAM_ETHERTYPE = bytes.fromhex("88 b6")
PAYLOAD_BYTES = 1024
HEADER_BYTES = 14


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("binary", type=Path)
    parser.add_argument("output_dir", type=Path)
    parser.add_argument("--memory-bytes", type=lambda value: int(value, 0),
                        default=128 * 1024)
    parser.add_argument("--base", type=lambda value: int(value, 0),
                        default=0x80000000)
    args = parser.parse_args()

    program = args.binary.read_bytes()
    if len(program) > args.memory_bytes:
        raise ValueError(
            f"program is {len(program)} bytes, memory image is "
            f"{args.memory_bytes} bytes"
        )

    args.output_dir.mkdir(parents=True, exist_ok=True)
    frame_count = max(1, (len(program) + PAYLOAD_BYTES - 1) // PAYLOAD_BYTES)
    payload_image = program.ljust(frame_count * PAYLOAD_BYTES, b"\x00")
    memory_image = program.ljust(args.memory_bytes, b"\x00")

    mem64_path = args.output_dir / "stress_200k_dualhart_system.mem64"
    with mem64_path.open("w", encoding="ascii", newline="\n") as handle:
        for offset in range(0, len(memory_image), 8):
            word = int.from_bytes(memory_image[offset:offset + 8], "little")
            handle.write(f"{word:016x}\n")

    frames = bytearray()
    frame_offsets = []
    for index in range(frame_count):
        payload = payload_image[
            index * PAYLOAD_BYTES:(index + 1) * PAYLOAD_BYTES
        ]
        frame_offsets.append(len(frames))
        frames.extend(PROGRAM_DEST + HOST_SOURCE + PROGRAM_ETHERTYPE + payload)

    frames_bin_path = args.output_dir / "stress_200k_program_frames.bin"
    frames_bin_path.write_bytes(frames)

    frames_mem16_path = args.output_dir / "stress_200k_program_frames.mem16"
    with frames_mem16_path.open("w", encoding="ascii", newline="\n") as handle:
        for offset in range(0, len(frames), 2):
            word = int.from_bytes(frames[offset:offset + 2], "little")
            handle.write(f"{word:04x}\n")

    params_path = args.output_dir / "stress_200k_program_params.svh"
    params_path.write_text(
        "/* Generated by make_program_images.py. */\n"
        f"`define STRESS_PROGRAM_BYTES {len(program)}\n"
        f"`define STRESS_PROGRAM_FRAME_COUNT {frame_count}\n"
        f"`define STRESS_PROGRAM_WORD_COUNT "
        f"{frame_count * ((HEADER_BYTES + PAYLOAD_BYTES) // 2)}\n",
        encoding="ascii",
    )

    manifest = {
        "ddr_base": f"0x{args.base:08x}",
        "program_bytes": len(program),
        "padded_payload_bytes": len(payload_image),
        "frame_count": frame_count,
        "frame_bytes": HEADER_BYTES + PAYLOAD_BYTES,
        "frame_words_16": (HEADER_BYTES + PAYLOAD_BYTES) // 2,
        "destination_mac": PROGRAM_DEST.hex(":"),
        "source_mac": HOST_SOURCE.hex(":"),
        "ethertype": f"0x{int.from_bytes(PROGRAM_ETHERTYPE, 'big'):04x}",
        "frame_offsets": frame_offsets,
    }
    (args.output_dir / "image_manifest.json").write_text(
        json.dumps(manifest, indent=2) + "\n", encoding="utf-8"
    )
    print(json.dumps(manifest, indent=2))


if __name__ == "__main__":
    main()
