// Vivado synthesis declaration for the Synplify-generated EDIF cell.
// The behavioral RTL definition remains enabled only for simulation.
(* black_box = "true" *)
module eh2_veer_wrapper (
  input clk,
  input rst_l,
  input dbg_rst_l,
  input [31:1] rst_vec,
  input nmi_int,
  input [31:1] nmi_vec,
  input [31:1] jtag_id,
  output [63:0] trace_rv_i_insn_ip,
  output [63:0] trace_rv_i_address_ip,
  output [1:0] trace_rv_i_valid_ip,
  output [1:0] trace_rv_i_exception_ip,
  output [4:0] trace_rv_i_ecause_ip,
  output [1:0] trace_rv_i_interrupt_ip,
  output [31:0] trace_rv_i_tval_ip,

  output lsu_axi_awvalid,
  input lsu_axi_awready,
  output [3:0] lsu_axi_awid,
  output [31:0] lsu_axi_awaddr,
  output [3:0] lsu_axi_awregion,
  output [7:0] lsu_axi_awlen,
  output [2:0] lsu_axi_awsize,
  output [1:0] lsu_axi_awburst,
  output lsu_axi_awlock,
  output [3:0] lsu_axi_awcache,
  output [2:0] lsu_axi_awprot,
  output [3:0] lsu_axi_awqos,
  output lsu_axi_wvalid,
  input lsu_axi_wready,
  output [63:0] lsu_axi_wdata,
  output [7:0] lsu_axi_wstrb,
  output lsu_axi_wlast,
  input lsu_axi_bvalid,
  output lsu_axi_bready,
  input [1:0] lsu_axi_bresp,
  input [3:0] lsu_axi_bid,
  output lsu_axi_arvalid,
  input lsu_axi_arready,
  output [3:0] lsu_axi_arid,
  output [31:0] lsu_axi_araddr,
  output [3:0] lsu_axi_arregion,
  output [7:0] lsu_axi_arlen,
  output [2:0] lsu_axi_arsize,
  output [1:0] lsu_axi_arburst,
  output lsu_axi_arlock,
  output [3:0] lsu_axi_arcache,
  output [2:0] lsu_axi_arprot,
  output [3:0] lsu_axi_arqos,
  input lsu_axi_rvalid,
  output lsu_axi_rready,
  input [3:0] lsu_axi_rid,
  input [63:0] lsu_axi_rdata,
  input [1:0] lsu_axi_rresp,
  input lsu_axi_rlast,

  output ifu_axi_awvalid,
  input ifu_axi_awready,
  output [3:0] ifu_axi_awid,
  output [31:0] ifu_axi_awaddr,
  output [3:0] ifu_axi_awregion,
  output [7:0] ifu_axi_awlen,
  output [2:0] ifu_axi_awsize,
  output [1:0] ifu_axi_awburst,
  output ifu_axi_awlock,
  output [3:0] ifu_axi_awcache,
  output [2:0] ifu_axi_awprot,
  output [3:0] ifu_axi_awqos,
  output ifu_axi_wvalid,
  input ifu_axi_wready,
  output [63:0] ifu_axi_wdata,
  output [7:0] ifu_axi_wstrb,
  output ifu_axi_wlast,
  input ifu_axi_bvalid,
  output ifu_axi_bready,
  input [1:0] ifu_axi_bresp,
  input [3:0] ifu_axi_bid,
  output ifu_axi_arvalid,
  input ifu_axi_arready,
  output [3:0] ifu_axi_arid,
  output [31:0] ifu_axi_araddr,
  output [3:0] ifu_axi_arregion,
  output [7:0] ifu_axi_arlen,
  output [2:0] ifu_axi_arsize,
  output [1:0] ifu_axi_arburst,
  output ifu_axi_arlock,
  output [3:0] ifu_axi_arcache,
  output [2:0] ifu_axi_arprot,
  output [3:0] ifu_axi_arqos,
  input ifu_axi_rvalid,
  output ifu_axi_rready,
  input [3:0] ifu_axi_rid,
  input [63:0] ifu_axi_rdata,
  input [1:0] ifu_axi_rresp,
  input ifu_axi_rlast,

  output sb_axi_awvalid,
  input sb_axi_awready,
  output [0:0] sb_axi_awid,
  output [31:0] sb_axi_awaddr,
  output [3:0] sb_axi_awregion,
  output [7:0] sb_axi_awlen,
  output [2:0] sb_axi_awsize,
  output [1:0] sb_axi_awburst,
  output sb_axi_awlock,
  output [3:0] sb_axi_awcache,
  output [2:0] sb_axi_awprot,
  output [3:0] sb_axi_awqos,
  output sb_axi_wvalid,
  input sb_axi_wready,
  output [63:0] sb_axi_wdata,
  output [7:0] sb_axi_wstrb,
  output sb_axi_wlast,
  input sb_axi_bvalid,
  output sb_axi_bready,
  input [1:0] sb_axi_bresp,
  input [0:0] sb_axi_bid,
  output sb_axi_arvalid,
  input sb_axi_arready,
  output [0:0] sb_axi_arid,
  output [31:0] sb_axi_araddr,
  output [3:0] sb_axi_arregion,
  output [7:0] sb_axi_arlen,
  output [2:0] sb_axi_arsize,
  output [1:0] sb_axi_arburst,
  output sb_axi_arlock,
  output [3:0] sb_axi_arcache,
  output [2:0] sb_axi_arprot,
  output [3:0] sb_axi_arqos,
  input sb_axi_rvalid,
  output sb_axi_rready,
  input [0:0] sb_axi_rid,
  input [63:0] sb_axi_rdata,
  input [1:0] sb_axi_rresp,
  input sb_axi_rlast,

  input dma_axi_awvalid,
  output dma_axi_awready,
  input [0:0] dma_axi_awid,
  input [31:0] dma_axi_awaddr,
  input [2:0] dma_axi_awsize,
  input [2:0] dma_axi_awprot,
  input [7:0] dma_axi_awlen,
  input [1:0] dma_axi_awburst,
  input dma_axi_wvalid,
  output dma_axi_wready,
  input [63:0] dma_axi_wdata,
  input [7:0] dma_axi_wstrb,
  input dma_axi_wlast,
  output dma_axi_bvalid,
  input dma_axi_bready,
  output [1:0] dma_axi_bresp,
  output [0:0] dma_axi_bid,
  input dma_axi_arvalid,
  output dma_axi_arready,
  input [0:0] dma_axi_arid,
  input [31:0] dma_axi_araddr,
  input [2:0] dma_axi_arsize,
  input [2:0] dma_axi_arprot,
  input [7:0] dma_axi_arlen,
  input [1:0] dma_axi_arburst,
  output dma_axi_rvalid,
  input dma_axi_rready,
  output [0:0] dma_axi_rid,
  output [63:0] dma_axi_rdata,
  output [1:0] dma_axi_rresp,
  output dma_axi_rlast,

  input lsu_bus_clk_en,
  input ifu_bus_clk_en,
  input dbg_bus_clk_en,
  input dma_bus_clk_en,
  input [95:0] dccm_ext_in_pkt,
  input [47:0] iccm_ext_in_pkt,
  input [23:0] btb_ext_in_pkt,
  input [95:0] ic_data_ext_in_pkt,
  input [47:0] ic_tag_ext_in_pkt,
  input [0:0] timer_int,
  input [0:0] soft_int,
  input [127:1] extintsrc_req,
  output [1:0] dec_tlu_perfcnt0,
  output [1:0] dec_tlu_perfcnt1,
  output [1:0] dec_tlu_perfcnt2,
  output [1:0] dec_tlu_perfcnt3,
  input jtag_tck,
  input jtag_tms,
  input jtag_tdi,
  input jtag_trst_n,
  output jtag_tdo,
  input [31:4] core_id,
  input [0:0] mpc_debug_halt_req,
  input [0:0] mpc_debug_run_req,
  input [0:0] mpc_reset_run_req,
  output [0:0] mpc_debug_halt_ack,
  output [0:0] mpc_debug_run_ack,
  output [0:0] debug_brkpt_status,
  output [0:0] dec_tlu_mhartstart,
  input [0:0] i_cpu_halt_req,
  output [0:0] o_cpu_halt_ack,
  output [0:0] o_cpu_halt_status,
  output [0:0] o_debug_mode_status,
  input [0:0] i_cpu_run_req,
  output [0:0] o_cpu_run_ack,
  input scan_mode,
  input mbist_mode
);
endmodule
