`timescale 1ns/1ps

module dual_ddr_mig_wrapper (
  input  logic hard_resetn,
  input  logic c0_sys_clk_p,
  input  logic c0_sys_clk_n,
  input  logic c1_sys_clk_p,
  input  logic c1_sys_clk_n,
  output logic c0_ui_clk,
  output logic c0_ui_resetn,
  output logic c0_calib_done,
  output logic c1_ui_clk,
  output logic c1_ui_resetn,
  output logic c1_calib_done,
  axi4_if.slave c0_axi,
  axi4_if.slave c1_axi,

  output logic        c0_ddr4_act_n,
  output logic [16:0] c0_ddr4_adr,
  output logic [1:0]  c0_ddr4_ba,
  output logic [1:0]  c0_ddr4_bg,
  output logic [0:0]  c0_ddr4_cke,
  output logic [0:0]  c0_ddr4_odt,
  output logic [0:0]  c0_ddr4_cs_n,
  output logic [0:0]  c0_ddr4_ck_t,
  output logic [0:0]  c0_ddr4_ck_c,
  output logic        c0_ddr4_reset_n,
  inout  wire [8:0]   c0_ddr4_dm_dbi_n,
  inout  wire [71:0]  c0_ddr4_dq,
  inout  wire [8:0]   c0_ddr4_dqs_c,
  inout  wire [8:0]   c0_ddr4_dqs_t,

  output logic        c1_ddr4_act_n,
  output logic [16:0] c1_ddr4_adr,
  output logic [1:0]  c1_ddr4_ba,
  output logic [1:0]  c1_ddr4_bg,
  output logic [0:0]  c1_ddr4_cke,
  output logic [0:0]  c1_ddr4_odt,
  output logic [0:0]  c1_ddr4_cs_n,
  output logic [0:0]  c1_ddr4_ck_t,
  output logic [0:0]  c1_ddr4_ck_c,
  output logic        c1_ddr4_reset_n,
  inout  wire [8:0]   c1_ddr4_dm_dbi_n,
  inout  wire [71:0]  c1_ddr4_dq,
  inout  wire [8:0]   c1_ddr4_dqs_c,
  inout  wire [8:0]   c1_ddr4_dqs_t
);
  logic c0_ui_rst;
  logic c1_ui_rst;
  assign c0_ui_resetn = c0_calib_done && !c0_ui_rst;
  assign c1_ui_resetn = c1_calib_done && !c1_ui_rst;

  ddr4_0 ddr0_i (
    .c0_init_calib_complete(c0_calib_done), .dbg_clk(),
    .c0_sys_clk_p, .c0_sys_clk_n, .dbg_bus(),
    .c0_ddr4_adr, .c0_ddr4_ba, .c0_ddr4_cke, .c0_ddr4_cs_n,
    .c0_ddr4_dm_dbi_n, .c0_ddr4_dq, .c0_ddr4_dqs_c, .c0_ddr4_dqs_t,
    .c0_ddr4_odt, .c0_ddr4_bg, .c0_ddr4_reset_n, .c0_ddr4_act_n,
    .c0_ddr4_ck_c, .c0_ddr4_ck_t,
    .c0_ddr4_ui_clk(c0_ui_clk), .c0_ddr4_ui_clk_sync_rst(c0_ui_rst),
    .c0_ddr4_aresetn(c0_ui_resetn),
    .c0_ddr4_s_axi_ctrl_awvalid(1'b0), .c0_ddr4_s_axi_ctrl_awready(),
    .c0_ddr4_s_axi_ctrl_awaddr(32'b0),
    .c0_ddr4_s_axi_ctrl_wvalid(1'b0), .c0_ddr4_s_axi_ctrl_wready(),
    .c0_ddr4_s_axi_ctrl_wdata(32'b0),
    .c0_ddr4_s_axi_ctrl_bvalid(), .c0_ddr4_s_axi_ctrl_bready(1'b1),
    .c0_ddr4_s_axi_ctrl_bresp(),
    .c0_ddr4_s_axi_ctrl_arvalid(1'b0), .c0_ddr4_s_axi_ctrl_arready(),
    .c0_ddr4_s_axi_ctrl_araddr(32'b0),
    .c0_ddr4_s_axi_ctrl_rvalid(), .c0_ddr4_s_axi_ctrl_rready(1'b1),
    .c0_ddr4_s_axi_ctrl_rdata(), .c0_ddr4_s_axi_ctrl_rresp(),
    .c0_ddr4_interrupt(),
    .c0_ddr4_s_axi_awid(c0_axi.awid),
    .c0_ddr4_s_axi_awaddr(c0_axi.awaddr),
    .c0_ddr4_s_axi_awlen(c0_axi.awlen),
    .c0_ddr4_s_axi_awsize(c0_axi.awsize),
    .c0_ddr4_s_axi_awburst(c0_axi.awburst),
    .c0_ddr4_s_axi_awlock(c0_axi.awlock),
    .c0_ddr4_s_axi_awcache(c0_axi.awcache),
    .c0_ddr4_s_axi_awprot(c0_axi.awprot),
    .c0_ddr4_s_axi_awqos(c0_axi.awqos),
    .c0_ddr4_s_axi_awvalid(c0_axi.awvalid),
    .c0_ddr4_s_axi_awready(c0_axi.awready),
    .c0_ddr4_s_axi_wdata(c0_axi.wdata),
    .c0_ddr4_s_axi_wstrb(c0_axi.wstrb),
    .c0_ddr4_s_axi_wlast(c0_axi.wlast),
    .c0_ddr4_s_axi_wvalid(c0_axi.wvalid),
    .c0_ddr4_s_axi_wready(c0_axi.wready),
    .c0_ddr4_s_axi_bready(c0_axi.bready),
    .c0_ddr4_s_axi_bid(c0_axi.bid),
    .c0_ddr4_s_axi_bresp(c0_axi.bresp),
    .c0_ddr4_s_axi_bvalid(c0_axi.bvalid),
    .c0_ddr4_s_axi_arid(c0_axi.arid),
    .c0_ddr4_s_axi_araddr(c0_axi.araddr),
    .c0_ddr4_s_axi_arlen(c0_axi.arlen),
    .c0_ddr4_s_axi_arsize(c0_axi.arsize),
    .c0_ddr4_s_axi_arburst(c0_axi.arburst),
    .c0_ddr4_s_axi_arlock(c0_axi.arlock),
    .c0_ddr4_s_axi_arcache(c0_axi.arcache),
    .c0_ddr4_s_axi_arprot(c0_axi.arprot),
    .c0_ddr4_s_axi_arqos(c0_axi.arqos),
    .c0_ddr4_s_axi_arvalid(c0_axi.arvalid),
    .c0_ddr4_s_axi_arready(c0_axi.arready),
    .c0_ddr4_s_axi_rready(c0_axi.rready),
    .c0_ddr4_s_axi_rlast(c0_axi.rlast),
    .c0_ddr4_s_axi_rvalid(c0_axi.rvalid),
    .c0_ddr4_s_axi_rresp(c0_axi.rresp),
    .c0_ddr4_s_axi_rid(c0_axi.rid),
    .c0_ddr4_s_axi_rdata(c0_axi.rdata),
    .sys_rst(!hard_resetn)
  );

  ddr4_1 ddr1_i (
    .c0_init_calib_complete(c1_calib_done), .dbg_clk(),
    .c0_sys_clk_p(c1_sys_clk_p), .c0_sys_clk_n(c1_sys_clk_n), .dbg_bus(),
    .c0_ddr4_adr(c1_ddr4_adr), .c0_ddr4_ba(c1_ddr4_ba),
    .c0_ddr4_cke(c1_ddr4_cke), .c0_ddr4_cs_n(c1_ddr4_cs_n),
    .c0_ddr4_dm_dbi_n(c1_ddr4_dm_dbi_n), .c0_ddr4_dq(c1_ddr4_dq),
    .c0_ddr4_dqs_c(c1_ddr4_dqs_c), .c0_ddr4_dqs_t(c1_ddr4_dqs_t),
    .c0_ddr4_odt(c1_ddr4_odt), .c0_ddr4_bg(c1_ddr4_bg),
    .c0_ddr4_reset_n(c1_ddr4_reset_n), .c0_ddr4_act_n(c1_ddr4_act_n),
    .c0_ddr4_ck_c(c1_ddr4_ck_c), .c0_ddr4_ck_t(c1_ddr4_ck_t),
    .c0_ddr4_ui_clk(c1_ui_clk), .c0_ddr4_ui_clk_sync_rst(c1_ui_rst),
    .c0_ddr4_aresetn(c1_ui_resetn),
    .c0_ddr4_s_axi_ctrl_awvalid(1'b0), .c0_ddr4_s_axi_ctrl_awready(),
    .c0_ddr4_s_axi_ctrl_awaddr(32'b0),
    .c0_ddr4_s_axi_ctrl_wvalid(1'b0), .c0_ddr4_s_axi_ctrl_wready(),
    .c0_ddr4_s_axi_ctrl_wdata(32'b0),
    .c0_ddr4_s_axi_ctrl_bvalid(), .c0_ddr4_s_axi_ctrl_bready(1'b1),
    .c0_ddr4_s_axi_ctrl_bresp(),
    .c0_ddr4_s_axi_ctrl_arvalid(1'b0), .c0_ddr4_s_axi_ctrl_arready(),
    .c0_ddr4_s_axi_ctrl_araddr(32'b0),
    .c0_ddr4_s_axi_ctrl_rvalid(), .c0_ddr4_s_axi_ctrl_rready(1'b1),
    .c0_ddr4_s_axi_ctrl_rdata(), .c0_ddr4_s_axi_ctrl_rresp(),
    .c0_ddr4_interrupt(),
    .c0_ddr4_s_axi_awid(c1_axi.awid),
    .c0_ddr4_s_axi_awaddr(c1_axi.awaddr),
    .c0_ddr4_s_axi_awlen(c1_axi.awlen),
    .c0_ddr4_s_axi_awsize(c1_axi.awsize),
    .c0_ddr4_s_axi_awburst(c1_axi.awburst),
    .c0_ddr4_s_axi_awlock(c1_axi.awlock),
    .c0_ddr4_s_axi_awcache(c1_axi.awcache),
    .c0_ddr4_s_axi_awprot(c1_axi.awprot),
    .c0_ddr4_s_axi_awqos(c1_axi.awqos),
    .c0_ddr4_s_axi_awvalid(c1_axi.awvalid),
    .c0_ddr4_s_axi_awready(c1_axi.awready),
    .c0_ddr4_s_axi_wdata(c1_axi.wdata),
    .c0_ddr4_s_axi_wstrb(c1_axi.wstrb),
    .c0_ddr4_s_axi_wlast(c1_axi.wlast),
    .c0_ddr4_s_axi_wvalid(c1_axi.wvalid),
    .c0_ddr4_s_axi_wready(c1_axi.wready),
    .c0_ddr4_s_axi_bready(c1_axi.bready),
    .c0_ddr4_s_axi_bid(c1_axi.bid),
    .c0_ddr4_s_axi_bresp(c1_axi.bresp),
    .c0_ddr4_s_axi_bvalid(c1_axi.bvalid),
    .c0_ddr4_s_axi_arid(c1_axi.arid),
    .c0_ddr4_s_axi_araddr(c1_axi.araddr),
    .c0_ddr4_s_axi_arlen(c1_axi.arlen),
    .c0_ddr4_s_axi_arsize(c1_axi.arsize),
    .c0_ddr4_s_axi_arburst(c1_axi.arburst),
    .c0_ddr4_s_axi_arlock(c1_axi.arlock),
    .c0_ddr4_s_axi_arcache(c1_axi.arcache),
    .c0_ddr4_s_axi_arprot(c1_axi.arprot),
    .c0_ddr4_s_axi_arqos(c1_axi.arqos),
    .c0_ddr4_s_axi_arvalid(c1_axi.arvalid),
    .c0_ddr4_s_axi_arready(c1_axi.arready),
    .c0_ddr4_s_axi_rready(c1_axi.rready),
    .c0_ddr4_s_axi_rlast(c1_axi.rlast),
    .c0_ddr4_s_axi_rvalid(c1_axi.rvalid),
    .c0_ddr4_s_axi_rresp(c1_axi.rresp),
    .c0_ddr4_s_axi_rid(c1_axi.rid),
    .c0_ddr4_s_axi_rdata(c1_axi.rdata),
    .sys_rst(!hard_resetn)
  );
endmodule

